### ISSUE TITLE
Can I play this awesome game in local PC?

### ISSUE THREAD

**Issue by Domosed-gamin** [branw/super-serif-bros#1] opened 2020-04-12 15:47 UTC
Hi! Can I play this awesome game in local PC? Without telnet.

**Comment by branw** [comment] 2020-05-23 05:48
I just started working on a version of the game that runs in Notepad of all things (it injects into the process and takes control):

![notepad_1xDeuyyDt1](https://user-images.githubusercontent.com/2104778/82722738-4d5a9c00-9c97-11ea-99cf-b9ccfb9c315d.png)

I'll notify you once I get an initial release out!

**Comment by Domosed-gamin** [comment] 2020-05-23 05:56
Ok. Please make support linux.

**Comment by Domosed-gamin** [comment] 2021-04-29 17:03
```
ringo@qwerty:~/Загрузки$ cd sans-serif-bros-master/
ringo@qwerty:~/Загрузки/sans-serif-bros-master$ ls
ext  include  levels  LICENSE  Makefile  README.md  src
ringo@qwerty:~/Загрузки/sans-serif-bros-master$ make
gcc -g -Wall -std=c99 -fsanitize=address -fsanitize=undefined -O0 -fno-omit-frame-pointer   -c -o src/main.o src/main.c
src/main.c:7:17: fatal error: env.h: No such file or directory
 #include <env.h>
                 ^
compilation terminated.
<встроенное>: ошибка выполнения рецепта для цели «src/main.o»
make: *** [src/main.o] Ошибка 1
```
I try to compile the project and I fail. What is env.h header? I can't found it.

**Comment by branw** [comment] 2021-04-29 22:08
> I try to compile the project and I fail. What is env.h header? I can't found it.

The GitHub Actions container is [running into the same problem](https://github.com/branw/sans-serif-bros/runs/2470743017), but I can't reproduce it yet. I am investigating.

**Comment by branw** [comment] 2021-04-29 23:00
The build issues should be fixed now. To build, you just run:

```
make
```

Then to play the "standalone" version without Telnet, run:

```
./ssb -s
```

I haven't touched this project in a long time, so I'm not sure if it's really playable at the moment. I do plan to continue working on it soon though.

**Closed as completed by branw** 2021-04-29 23:00 UTC
